from pathlib import Path
from playwright.sync_api import sync_playwright, expect

APP = Path(__file__).with_name('daily-todo.html')
assert APP.exists(), 'Daily to-do website has not been created yet'
with sync_playwright() as p:
    browser = p.chromium.launch(channel='msedge', headless=True)
    page = browser.new_page(viewport={'width': 1200, 'height': 900})
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto(APP.as_uri())
    page.locator('#task-input').fill('Buy groceries')
    page.get_by_role('button', name='Add task', exact=True).click()
    expect(page.locator('.task-title')).to_have_text(['Buy groceries'])
    page.locator('#task-input').fill('   ')
    page.get_by_role('button', name='Add task', exact=True).click()
    expect(page.locator('.task-title')).to_have_count(1)
    print('PASS: add task and reject whitespace')
    page.reload()
    expect(page.locator('.task-title')).to_have_text(['Buy groceries'])
    current_day = page.locator('#day').input_value()
    assert current_day
    page.get_by_role('button', name='Next day', exact=True).click()
    expect(page.locator('.task-title')).to_have_count(0)
    page.locator('#task-input').fill('Tomorrow task')
    page.get_by_role('button', name='Add task', exact=True).click()
    page.get_by_role('button', name='Previous day', exact=True).click()
    expect(page.locator('.task-title')).to_have_text(['Buy groceries'])
    page.reload()
    expect(page.locator('.task-title')).to_have_text(['Buy groceries'])
    print('PASS: per-day lists and persistence after reload')
    expect(page.get_by_role('checkbox', name='Complete Buy groceries')).to_have_count(1)
    page.get_by_role('checkbox', name='Complete Buy groceries').check()
    expect(page.locator('#summary')).to_have_text('1 of 1 completed')
    expect(page.locator('#progress')).to_have_attribute('value', '100')
    page.reload()
    expect(page.get_by_role('checkbox')).to_be_checked()
    page.get_by_role('checkbox').uncheck()
    expect(page.locator('#summary')).to_have_text('0 of 1 completed')
    print('PASS: complete, uncomplete, progress and saved completion')
    page.get_by_role('button', name='Done', exact=True).click()
    expect(page.locator('.task-title')).to_have_count(0)
    page.get_by_role('button', name='To do', exact=True).click()
    expect(page.locator('.task-title')).to_have_count(1)
    # Clicking removes the row from this filter; check() waits for it to remain.
    page.get_by_role('checkbox').click()
    expect(page.locator('.task-title')).to_have_count(0)
    page.get_by_role('button', name='Done', exact=True).click()
    expect(page.locator('.task-title')).to_have_count(1)
    page.get_by_role('button', name='Clear completed', exact=True).click()
    expect(page.locator('.task-title')).to_have_count(0)
    page.get_by_role('button', name='All', exact=True).click()
    page.locator('#task-input').fill('Delete me')
    page.locator('#task-input').press('Enter')
    page.get_by_role('button', name='Delete Delete me', exact=True).click()
    expect(page.locator('.task-title')).to_have_count(0)
    page.reload()
    expect(page.locator('.task-title')).to_have_count(0)
    page.get_by_role('button', name='Next day', exact=True).click()
    expect(page.locator('.task-title')).to_have_text(['Tomorrow task'])
    page.get_by_role('button', name='Today', exact=True).click()
    expect(page.locator('#day')).to_have_value(current_day)
    print('PASS: filters, clear completed and deletion leave other days intact')
    page.locator('#task-input').fill('<img src=x onerror=alert(1)>')
    page.locator('#task-input').press('Enter')
    expect(page.locator('#tasks img')).to_have_count(0)
    expect(page.locator('.task-title')).to_have_text(['<img src=x onerror=alert(1)>'])
    page.locator('#day').fill('2028-02-29')
    page.locator('#day').dispatch_event('change')
    page.get_by_role('button', name='Next day', exact=True).click()
    expect(page.locator('#day')).to_have_value('2028-03-01')
    page.get_by_role('button', name='Previous day', exact=True).click()
    expect(page.locator('#day')).to_have_value('2028-02-29')
    page.locator('#day').fill('')
    page.locator('#day').dispatch_event('change')
    expect(page.locator('#day')).to_have_value('2028-02-29')
    print('PASS: task text is safe, leap-day navigation and empty date handling')
    for text in ['Plan the day', 'Take a short walk', 'Read a few pages']:
        page.locator('#task-input').fill(text)
        page.locator('#task-input').press('Enter')
    page.get_by_role('checkbox').first.check()
    page.screenshot(path=str(APP.with_name('daily-todo-desktop.png')), full_page=True)
    page.set_viewport_size({'width': 375, 'height': 812})
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    assert abs(page.locator('#prev').bounding_box()['y'] - page.locator('#next').bounding_box()['y']) < 2, 'Date navigation buttons must stay on the same row'
    page.screenshot(path=str(APP.with_name('daily-todo-mobile.png')), full_page=True)
    print('PASS: 375px mobile viewport without horizontal overflow')
    page.evaluate("localStorage.setItem('daylist.daily.v1', '{broken')")
    page.reload()
    expect(page.locator('#notice')).to_be_visible()
    page.locator('#task-input').fill('Temporary task')
    page.locator('#task-input').press('Enter')
    expect(page.locator('.task-title')).to_have_text(['Temporary task'])
    assert page.evaluate("localStorage.getItem('daylist.daily.v1')") == '{broken'
    page.evaluate("localStorage.removeItem('daylist.daily.v1')")
    page.reload()
    page.evaluate("() => { Storage.prototype.setItem = function(){throw new Error('Quota exceeded')}; }")
    page.locator('#task-input').fill('Unsaved task')
    page.locator('#task-input').press('Enter')
    expect(page.locator('#notice')).to_be_visible()
    expect(page.locator('.task-title')).to_have_text(['Unsaved task'])
    print('PASS: corrupt storage protected and write failures surfaced')
    assert not errors, errors
    print('PASS: no browser JavaScript errors')
    browser.close()
